name             'confyaml'
maintainer       'Roy Ratcliffe'
maintainer_email 'roy@pioneeringsoftware.co.uk'
license          'All rights reserved'
description      'Installs/Configures confyaml'
long_description 'Installs/Configures confyaml'
version          '0.1.7'
