name             'confyaml'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures confyaml'
long_description 'Installs/Configures confyaml'
version          '0.1.1'
